spring:
  application:
    name: hotel

  datasource:
    url: jdbc:postgresql://172.17.0.3:5432/hotel
    username: postgres
    password: mysecretpassword
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

logging:
  level:
    org:
      springframework:
        security: DEBUG
